import React, { createContext, useContext, useState } from 'react';

export type Language = 'EN' | 'AR' | 'FR';

const translations = {
  EN: {
    appTitle: 'Gharsa AI',
    tagline: 'The Soul of Soil, the Mind of AI',
    getStarted: 'Get Started',
    login: 'Login',
    status: 'Status',
    optimal: 'Optimal',
    biosphereCore: 'Biosphere Core',
    liveSync: 'LIVE SYNC',
    moisture: 'Moisture',
    temperature: 'Temperature',
    phLevel: 'pH Level',
    illuminance: 'Illuminance',
    nitrogen: 'Nitrogen',
    phosphorus: 'Phosphorus',
    potassium: 'Potassium',
    conditionsStable: 'Conditions stabilized for Tomato Batch A',
    agronomistAi: 'Agronomist AI',
    aiRecommendation: 'We detected unexpected humidity levels in Sector B. Increase ventilation to prevent fungus.',
    takeAction: 'Take Action',
    smartTools: 'Smart Tools',
    viewAll: 'VIEW ALL',
    irrigation: 'Irrigation',
    pestScan: 'Pest Scan',
    lighting: 'Lighting',
    fertilize: 'Fertilize',
    partlyCloudy: 'PARTLY CLOUDY',
    humidity: 'HUMIDITY',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot Password?',
    noAccount: "Don't have an account?",
    signUp: 'Sign Up',
    loginTitle: 'Login to Gharsa',
    aiPlantDiagnosis: 'AI Plant Diagnosis',
    scanSubtitle: 'Point your camera at the plant to identify pests, diseases, or nutrient deficiencies instantly.',
    startScanning: 'Start Scanning',
    communicationTitle: 'Community & Support',
    commSubtitle: 'Connect with experts and other farmers to share knowledge.',
    shareUpdate: "Share your farm's update...",
    photo: 'Photo',
    video: 'Video',
    askExpert: 'Ask Expert',
    like: 'Like',
    comment: 'Comment',
    hide: 'Hide',
    farmerLikes: 'Farmer Likes',
    comments: 'Comments',
    expert: 'EXPERT',
    writeReply: 'Write a reply...',
    selectRole: 'SELECT YOUR ROLE',
    farmer: 'Farmer',
    agronomist: 'Agronomist',
    comingSoon: 'COMING SOON',
    accountDetails: 'ACCOUNT DETAILS',
    fullName: 'Full Name',
    terms: 'Terms of Service',
    privacy: 'Privacy Policy',
    agreeTo: 'I agree to the',
    and: 'and',
    createAccount: 'Create Account',
    orRegisterWith: 'OR REGISTER WITH',
    joinFarmers: 'JOIN +12,000 FARMERS',
    alreadyHaveAccount: 'Already have an account?',
  },
  AR: {
    appTitle: 'غرسة الذكي',
    tagline: 'روح التربة، وعقل الذكاء الاصطناعي',
    getStarted: 'ابدأ الآن',
    login: 'تسجيل الدخول',
    status: 'الحالة',
    optimal: 'مثالي',
    biosphereCore: 'مركز الغلاف الحيوي',
    liveSync: 'مزامنة مباشرة',
    moisture: 'الرطوبة',
    temperature: 'الحرارة',
    phLevel: 'مستوى الحموضة',
    illuminance: 'الإضاءة',
    nitrogen: 'النيتروجين',
    phosphorus: 'الفسفور',
    potassium: 'البوتاسيوم',
    conditionsStable: 'الظروف مستقرة لمجموعة الطماطم أ',
    agronomistAi: 'خبير زراعي ذكي',
    aiRecommendation: 'اكتشفنا مستويات رطوبة غير متوقعة في القطاع ب. قم بزيادة التهوية لمنع الفطريات.',
    takeAction: 'اتخذ إجراء',
    smartTools: 'أدوات ذكية',
    viewAll: 'عرض الكل',
    irrigation: 'الري',
    pestScan: 'فحص الآفات',
    lighting: 'الإضاءة',
    fertilize: 'التسميد',
    partlyCloudy: 'غائم جزئياً',
    humidity: 'الرطوبة',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    forgotPassword: 'هل نسيت كلمة المرور؟',
    noAccount: 'ليس لديك حساب؟',
    signUp: 'إنشاء حساب',
    loginTitle: 'تسجيل الدخول إلى غرسة',
    aiPlantDiagnosis: 'تشخيص النبات بالذكاء الاصطناعي',
    scanSubtitle: 'وجه الكاميرا نحو النبات لتحديد الآفات أو الأمراض أو نقص المغذيات فوراً.',
    startScanning: 'بدء الفحص',
    communicationTitle: 'المجتمع والدعم',
    commSubtitle: 'تواصل مع الخبراء والمزارعين الآخرين لتبادل المعرفة.',
    shareUpdate: 'شارك آخر تحديثات مزرعتك...',
    photo: 'صورة',
    video: 'فيديو',
    askExpert: 'اسأل خبيراً',
    like: 'إعجاب',
    comment: 'تعليق',
    hide: 'إخفاء',
    farmerLikes: 'إعجابات المزارعين',
    comments: 'تعليقات',
    expert: 'خبير',
    writeReply: 'اكتب رداً...',
    selectRole: 'اختر دورك',
    farmer: 'مزارع',
    agronomist: 'مهندس زراعي',
    comingSoon: 'قريباً',
    accountDetails: 'تفاصيل الحساب',
    fullName: 'الاسم الكامل',
    terms: 'شروط الخدمة',
    privacy: 'سياسة الخصوصية',
    agreeTo: 'أوافق على',
    and: 'و',
    createAccount: 'إنشاء حساب',
    orRegisterWith: 'أو التسجيل بواسطة',
    joinFarmers: 'انضم إلى +12,000 مزارع',
    alreadyHaveAccount: 'لديك حساب بالفعل؟',
  },
  FR: {
    appTitle: 'Gharsa AI',
    tagline: "L'âme du sol, l'esprit de l'IA",
    getStarted: 'Commencer',
    login: 'Connexion',
    status: 'Statut',
    optimal: 'Optimal',
    biosphereCore: 'Cœur Biosphère',
    liveSync: 'SYNCHRO LIVE',
    moisture: 'Humidité',
    temperature: 'Température',
    phLevel: 'Niveau pH',
    illuminance: 'Éclairement',
    nitrogen: 'Azote',
    phosphorus: 'Phosphore',
    potassium: 'Potassium',
    conditionsStable: 'Conditions stabilisées pour le lot de tomates A',
    agronomistAi: 'Agronome IA',
    aiRecommendation: 'Nous avons détecté des niveaux d\'humidité inattendus dans le secteur B. Augmentez la ventilation pour prévenir les champignons.',
    takeAction: 'Agir',
    smartTools: 'Outils Intelligents',
    viewAll: 'VOIR TOUT',
    irrigation: 'Irrigation',
    pestScan: 'Scan ravageurs',
    lighting: 'Éclairage',
    fertilize: 'Fertiliser',
    partlyCloudy: 'PARTIELLEMENT NUAGEUX',
    humidity: 'HUMIDITÉ',
    email: 'E-mail',
    password: 'Mot de passe',
    forgotPassword: 'Mot de passe oublié ?',
    noAccount: "Vous n'avez pas de compte ?",
    signUp: "S'inscrire",
    loginTitle: 'Connexion à Gharsa',
    aiPlantDiagnosis: 'Diagnostic Végétal par IA',
    scanSubtitle: 'Pointez votre caméra vers la plante pour identifier instantanément les ravageurs, les maladies ou les carences.',
    startScanning: 'Démarrer le Scan',
    communicationTitle: 'Communauté & Support',
    commSubtitle: 'Connectez-vous avec des experts et d\'autres agriculteurs pour partager vos connaissances.',
    shareUpdate: 'Partagez les nouvelles de votre ferme...',
    photo: 'Photo',
    video: 'Vidéo',
    askExpert: 'Demander à un expert',
    like: 'J\'aime',
    comment: 'Commenter',
    hide: 'Masquer',
    farmerLikes: 'J\'aime des agriculteurs',
    comments: 'Commentaires',
    expert: 'EXPERT',
    writeReply: 'Écrire une réponse...',
    selectRole: 'SÉLECTIONNEZ VOTRE RÔLE',
    farmer: 'Agriculteur',
    agronomist: 'Agronome',
    comingSoon: 'BIENTÔT DISPONIBLE',
    accountDetails: 'DÉTAILS DU COMPTE',
    fullName: 'Nom complet',
    terms: 'Conditions d\'utilisation',
    privacy: 'Politique de confidentialité',
    agreeTo: 'J\'accepte les',
    and: 'et la',
    createAccount: 'Créer un compte',
    orRegisterWith: 'OU S\'INSCRIRE AVEC',
    joinFarmers: 'REJOIGNEZ +12 000 AGRICULTEURS',
    alreadyHaveAccount: 'Vous avez déjà un compte ?',
  },
};

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations.EN) => string;
};

const LanguageContext = createContext<LanguageContextType>({} as any);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('EN');

  const t = (key: keyof typeof translations.EN) => {
    return translations[language][key] || translations.EN[key];
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
